# -*- coding: utf-8 -*-
"""Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGeZbJ98ZYg4rE87l3586UXSur_fytq9
"""

!pip install transformers

from transformers import AutoModelForTokenClassification, pipeline, BertTokenizerFast

tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")

model_fine_tuned = AutoModelForTokenClassification.from_pretrained("ner_mountains_resulting")

# NER pipeline using the fine-tuned model
ner_mountains = pipeline("ner", model=model_fine_tuned, tokenizer=tokenizer, aggregation_strategy="simple")

example = "Mountains stand as monumental sentinels of the Earth, their towering peaks reaching toward the heavens. Each range tells a story of geological forces that shaped our planet over millions of years. From the jagged spires of the Himalayas, home to the world's highest peak, Mount Everest."

# Run NER on the example text
ner_results = ner_mountains(example)

# Print results
for result in ner_results:
    print(result)